import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { StorageService } from '../../core/services/storage.service';
import { EventItem, Notice, Platform, Priority, ReportStatus, Role, Subject, Task, TaskStatus, User } from '../../core/models/models';

interface NavItem { id: string; label: string; icon: string; }

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="app-shell" [class.dark]="darkMode">
      <aside class="sidebar" [class.open]="sidebarOpen">
        <div class="brand"><div class="brand-mark">CE</div><div><strong>Centro Escolar</strong><small>{{ role }}</small></div></div>
        <nav><button *ngFor="let item of navigation" class="nav-btn" [class.active]="activeSection === item.id" (click)="setSection(item.id)"><span>{{ item.icon }}</span>{{ item.label }}</button></nav>
        <div class="sidebar-bottom"><button class="nav-btn" (click)="toggleTheme()">◐ <span>{{ darkMode ? 'Modo claro' : 'Modo oscuro' }}</span></button><button class="nav-btn danger" (click)="logout()">↪ <span>Cerrar sesión</span></button></div>
      </aside>
      <main class="main">
        <header class="topbar"><button class="mobile-menu" (click)="sidebarOpen = !sidebarOpen">☰</button><div><span class="eyebrow">CENTRO ESCOLAR / {{ role }}</span><h1>{{ sectionTitle }}</h1></div><div class="topbar-tools"><select *ngIf="role === 'PADRE'" class="child-select" [(ngModel)]="parentChildId" aria-label="Alumno seleccionado"><option *ngFor="let child of parentChildren" [value]="child.id">{{ child.nombre }}</option></select><div class="user-chip"><span>{{ initials }}</span><div><strong>{{ user?.nombre }}</strong><small>{{ user?.email }}</small></div></div></div></header>
        <div class="content">
          <ng-container *ngIf="activeSection === 'inicio'"><section class="welcome"><div><span class="eyebrow">{{ greeting }}</span><h2>{{ homeTitle }}</h2><p>Una vista rápida de lo que requiere tu atención hoy.</p></div><span class="date-pill">{{ today | date:'EEEE, d MMMM' }}</span></section><div class="stats"><div class="stat" *ngFor="let stat of stats"><small>{{ stat.label }}</small><strong>{{ stat.value }}</strong><span>{{ stat.note }}</span></div></div><div class="dashboard-grid"><section class="card"><div class="section-head"><h3>{{ role === 'SOPORTE' ? 'Reportes recientes' : 'Próximas entregas' }}</h3><button class="text-btn" (click)="setSection(role === 'SOPORTE' ? 'reportes' : role === 'ADMIN' ? 'usuarios' : 'tareas')">Ver todo →</button></div><div *ngIf="role === 'SOPORTE'; else tasksHome"><div class="list-row" *ngFor="let report of reports.slice(0, 4)"><div><strong>#{{ report.id }} · {{ report.ubicacion }}</strong><small>{{ report.descripcion }}</small></div><span class="badge" [class]="'status-' + report.estado">{{ report.estado | titlecase }}</span></div></div><ng-template #tasksHome><div class="list-row" *ngFor="let task of upcomingTasks.slice(0, 4)"><div><strong>{{ task.titulo }}</strong><small>{{ task.materia }} · {{ task.fecha | date:'d MMM' }}</small></div><span class="badge priority-{{ task.prioridad }}">{{ task.prioridad }}</span></div><div class="empty" *ngIf="!upcomingTasks.length">No hay pendientes próximos.</div></ng-template></section><section class="card"><div class="section-head"><h3>Avisos</h3><button class="text-btn" (click)="setSection('avisos')">Ver todos →</button></div><div class="notice" *ngFor="let notice of notices.slice(0, 3)"><span class="notice-mark">!</span><div><strong>{{ notice.titulo }}</strong><small>{{ notice.contenido }}</small></div></div></section></div></ng-container>

          <ng-container *ngIf="activeSection === 'tareas'"><div class="section-head page-head"><div><span class="eyebrow">ORGANIZACIÓN</span><h2>Tareas</h2></div><button class="primary-btn" (click)="taskFormVisible = !taskFormVisible">＋ Nueva tarea</button></div><div class="toolbar"><select [(ngModel)]="taskFilter"><option value="TODAS">Todas</option><option value="PENDIENTE">Pendientes</option><option value="EN_PROGRESO">En progreso</option><option value="COMPLETADA">Completadas</option></select><span>{{ visibleTasks.length }} tareas</span></div><div class="inline-form" *ngIf="taskFormVisible"><input [(ngModel)]="newTaskTitle" placeholder="Título de la tarea"><input [(ngModel)]="newTaskSubject" placeholder="Materia"><input [(ngModel)]="newTaskDate" type="date"><select [(ngModel)]="newTaskPriority"><option value="BAJA">Prioridad baja</option><option value="MEDIA">Prioridad media</option><option value="ALTA">Prioridad alta</option></select><button class="primary-btn" (click)="createTask()">Guardar</button></div><section class="card"><div class="list-row" *ngFor="let task of visibleTasks"><div class="task-main"><input type="checkbox" [checked]="task.estado === 'COMPLETADA'" (change)="toggleTask(task)"><div><strong [class.completed]="task.estado === 'COMPLETADA'">{{ task.titulo }}</strong><small>{{ task.materia }} · Entrega {{ task.fecha | date:'d MMM y' }}</small></div></div><div class="row-actions"><span class="badge priority-{{ task.prioridad }}">{{ task.prioridad }}</span><button class="icon-btn" (click)="deleteTask(task)" title="Eliminar">×</button></div></div><div class="empty" *ngIf="!visibleTasks.length">No hay tareas para este filtro.</div></section></ng-container>

          <ng-container *ngIf="activeSection === 'materias'"><div class="section-head page-head"><div><span class="eyebrow">MI TRAYECTORIA</span><h2>Materias</h2></div><button class="primary-btn" *ngIf="role === 'ADMIN'" (click)="subjectFormVisible = !subjectFormVisible">＋ Nueva materia</button></div><div class="inline-form" *ngIf="subjectFormVisible"><input [(ngModel)]="newSubjectName" placeholder="Nombre"><input [(ngModel)]="newSubjectTeacher" placeholder="Profesor"><input [(ngModel)]="newSubjectGroup" placeholder="Grupo"><input [(ngModel)]="newSubjectRoom" placeholder="Aula"><button class="primary-btn" (click)="createSubject()">Guardar</button></div><div class="cards-grid"><article class="subject-card" *ngFor="let subject of subjects"><span class="subject-icon">▦</span><h3>{{ subject.nombre }}</h3><p>{{ subject.profesor }}</p><div><span>{{ subject.grupo }}</span><span>{{ subject.aula }}</span></div><small>{{ subject.horario }}</small></article></div></ng-container>

          <ng-container *ngIf="activeSection === 'plataformas'"><div class="section-head page-head"><div><span class="eyebrow">ACCESOS DIRECTOS</span><h2>Mis plataformas</h2></div><button class="primary-btn" (click)="platformFormVisible = !platformFormVisible">＋ Agregar plataforma</button></div><div class="inline-form" *ngIf="platformFormVisible"><input [(ngModel)]="newPlatformName" placeholder="Nombre"><input [(ngModel)]="newPlatformUrl" placeholder="https://..."><input [(ngModel)]="newPlatformDescription" placeholder="Descripción"><button class="primary-btn" (click)="createPlatform()">Guardar</button></div><div class="cards-grid"><article class="platform-card" *ngFor="let platform of platforms"><span class="platform-icon">↗</span><div><h3>{{ platform.nombre }}</h3><p>{{ platform.descripcion }}</p><small>{{ platform.tipo }}</small></div><a [href]="platform.url" target="_blank" rel="noopener" class="open-link">Abrir ↗</a></article></div></ng-container>

          <ng-container *ngIf="activeSection === 'calendario'"><div class="section-head page-head"><div><span class="eyebrow">ORGANIZA TU SEMANA</span><h2>Calendario</h2></div></div><div class="calendar card"><div class="calendar-head"><button class="icon-btn">‹</button><strong>Septiembre 2026</strong><button class="icon-btn">›</button></div><div class="calendar-grid"><span *ngFor="let day of weekDays">{{ day }}</span><div class="calendar-day" *ngFor="let day of calendarDays" [class.today]="day === 15"><b>{{ day }}</b><small *ngFor="let event of eventsForDay(day)">{{ event.titulo }}</small></div></div></div></ng-container>

          <ng-container *ngIf="activeSection === 'avisos'"><div class="section-head page-head"><div><span class="eyebrow">COMUNICACIÓN</span><h2>Avisos</h2></div><button class="primary-btn" *ngIf="role === 'ADMIN'" (click)="noticeFormVisible = !noticeFormVisible">＋ Publicar aviso</button></div><div class="inline-form" *ngIf="noticeFormVisible"><input [(ngModel)]="newNoticeTitle" placeholder="Título"><input [(ngModel)]="newNoticeContent" placeholder="Contenido"><select [(ngModel)]="newNoticeImportance"><option>MEDIA</option><option>ALTA</option></select><button class="primary-btn" (click)="createNotice()">Publicar</button></div><section class="card notice-list"><article *ngFor="let notice of notices"><span class="notice-mark">!</span><div><div class="notice-meta"><span>{{ notice.fecha | date:'d MMM y' }}</span><span class="badge" [class]="notice.importancia === 'ALTA' ? 'priority-ALTA' : ''">{{ notice.importancia }}</span></div><h3>{{ notice.titulo }}</h3><p>{{ notice.contenido }}</p><small>Publicado por {{ notice.autor }}</small></div></article></section></ng-container>

          <ng-container *ngIf="activeSection === 'reportes'"><div class="section-head page-head"><div><span class="eyebrow">SERVICIOS DEL CAMPUS</span><h2>Reportes de soporte</h2></div><button class="primary-btn" *ngIf="role === 'ALUMNO'" (click)="reportFormVisible = !reportFormVisible">＋ Nuevo reporte</button></div><div class="inline-form" *ngIf="reportFormVisible"><input [(ngModel)]="newReportLocation" placeholder="Ubicación"><input [(ngModel)]="newReportDescription" placeholder="Describe el problema"><button class="primary-btn" (click)="createReport()">Enviar reporte</button></div><section class="card"><div class="list-row report-line" *ngFor="let report of reports"><div><strong>#{{ report.id }} · {{ report.ubicacion }}</strong><small>{{ report.descripcion }} · {{ report.fecha | date:'d MMM y' }}</small><small *ngIf="report.comentarios.length">Último comentario: {{ report.comentarios[report.comentarios.length - 1] }}</small></div><div class="report-tools"><span class="badge" [class]="'status-' + report.estado">{{ report.estado.replace('_', ' ') }}</span><select *ngIf="role === 'SOPORTE'" [ngModel]="report.estado" (ngModelChange)="changeReport(report, $event)"><option>PENDIENTE</option><option>EN_REVISION</option><option>EN_PROCESO</option><option>RESUELTO</option></select><input *ngIf="role === 'SOPORTE'" placeholder="Comentario" (keyup.enter)="addComment(report, $any($event.target).value)"></div></div><div class="empty" *ngIf="!reports.length">No hay reportes.</div></section></ng-container>

          <ng-container *ngIf="activeSection === 'usuarios'"><div class="section-head page-head"><div><span class="eyebrow">CONTROL DE ACCESO</span><h2>Usuarios</h2></div><button class="primary-btn" (click)="userFormVisible = !userFormVisible">＋ Crear usuario</button></div><div class="inline-form" *ngIf="userFormVisible"><input [(ngModel)]="newUserName" placeholder="Nombre"><input [(ngModel)]="newUserEmail" placeholder="Correo"><select [(ngModel)]="newUserRole"><option>ALUMNO</option><option>PADRE</option><option>SOPORTE</option><option>ADMIN</option></select><button class="primary-btn" (click)="createUser()">Crear</button></div><section class="card table-wrap"><table><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th></th></tr></thead><tbody><tr *ngFor="let account of users"><td><strong>{{ account.nombre }}</strong><small>{{ account.email }}</small></td><td>{{ account.rol }}</td><td><span class="badge" [class.inactive]="!account.activo">{{ account.activo ? 'ACTIVO' : 'INACTIVO' }}</span></td><td><button class="text-btn" [disabled]="account.id === user?.id" (click)="toggleUser(account)">{{ account.activo ? 'Desactivar' : 'Activar' }}</button></td></tr></tbody></table></section></ng-container>
        </div>
      </main>
    </div>
  `
})
export class DashboardComponent implements OnInit {
  private readonly storage = inject(StorageService); private readonly auth = inject(AuthService);
  activeSection = 'inicio'; sidebarOpen = false; darkMode = false; taskFilter = 'TODAS'; taskFormVisible = false; subjectFormVisible = false; platformFormVisible = false; reportFormVisible = false; noticeFormVisible = false; userFormVisible = false;
  newTaskTitle = ''; newTaskSubject = ''; newTaskDate = '2026-09-20'; newTaskPriority: Priority = 'MEDIA'; newSubjectName = ''; newSubjectTeacher = ''; newSubjectGroup = '3°A'; newSubjectRoom = ''; newPlatformName = ''; newPlatformUrl = ''; newPlatformDescription = ''; newReportLocation = ''; newReportDescription = ''; newNoticeTitle = ''; newNoticeContent = ''; newNoticeImportance = 'MEDIA'; newUserName = ''; newUserEmail = ''; newUserRole: Role = 'ALUMNO';
  today = new Date('2026-09-15'); weekDays = ['LUN', 'MAR', 'MIÉ', 'JUE', 'VIE', 'SÁB', 'DOM']; calendarDays = Array.from({ length: 30 }, (_, index) => index + 1);

  get user(): User | null { return this.auth.currentUser(); } get role(): Role { return this.user?.rol ?? 'ALUMNO'; } get initials(): string { return (this.user?.nombre ?? 'CE').split(' ').map((part) => part[0]).slice(0, 2).join(''); }
  get navigation(): NavItem[] { if (this.role === 'ADMIN') return [{ id: 'inicio', label: 'Resumen', icon: '⌂' }, { id: 'usuarios', label: 'Usuarios', icon: '♙' }, { id: 'materias', label: 'Materias', icon: '▦' }, { id: 'avisos', label: 'Avisos', icon: '!' }, { id: 'reportes', label: 'Reportes', icon: '⚑' }]; if (this.role === 'SOPORTE') return [{ id: 'inicio', label: 'Resumen', icon: '⌂' }, { id: 'reportes', label: 'Reportes', icon: '⚑' }]; return [{ id: 'inicio', label: 'Inicio', icon: '⌂' }, { id: 'tareas', label: 'Tareas', icon: '✓' }, { id: 'calendario', label: 'Calendario', icon: '□' }, { id: 'materias', label: 'Materias', icon: '▦' }, { id: 'plataformas', label: 'Mis plataformas', icon: '↗' }, ...(this.role === 'ALUMNO' ? [{ id: 'reportes', label: 'Reportes', icon: '⚑' }] : []), { id: 'avisos', label: 'Avisos', icon: '!' }]; }
  get sectionTitle(): string { return this.navigation.find((item) => item.id === this.activeSection)?.label ?? 'Inicio'; } get greeting(): string { return this.role === 'ADMIN' ? 'PANEL DE CONTROL' : this.role === 'SOPORTE' ? 'CENTRO DE SOPORTE' : 'BUENOS DÍAS'; } get homeTitle(): string { return this.role === 'PADRE' ? 'Seguimiento familiar' : this.role === 'ADMIN' ? 'Resumen general' : this.role === 'SOPORTE' ? 'Estado de incidencias' : `Hola, ${this.user?.nombre.split(' ')[0]}`; }
  get users(): User[] { return this.storage.collection('usuarios'); } get subjects(): Subject[] { return this.storage.collection('materias'); } get platforms(): Platform[] { return this.storage.collection('plataformas'); } get notices(): Notice[] { return [...this.storage.collection('avisos')].sort((a, b) => b.fecha.localeCompare(a.fecha)); } get reports() { return [...this.storage.collection('reportes')].sort((a, b) => b.fecha.localeCompare(a.fecha)); }
  parentChildId = '';
  get parentChildren() { return this.storage.collection('alumnos').filter((child) => this.user?.hijos?.includes(child.id)); }
  get studentId(): string { return this.user?.alumnoId ?? 'a1'; } get selectedChildId(): string { return this.parentChildId || this.user?.hijos?.[0] || this.studentId; }
  get allTasks(): Task[] { return this.storage.collection('tareas'); } get visibleTasks(): Task[] { const ids = this.role === 'PADRE' ? [this.selectedChildId] : [this.studentId]; return this.allTasks.filter((task) => ids.includes(task.alumnoId) && (this.taskFilter === 'TODAS' || task.estado === this.taskFilter)).sort((a, b) => a.fecha.localeCompare(b.fecha)); } get upcomingTasks(): Task[] { return this.visibleTasks.filter((task) => task.estado !== 'COMPLETADA'); }
  get stats(): Array<{ label: string; value: string | number; note: string }> { const open = this.reports.filter((report) => report.estado !== 'RESUELTO').length; if (this.role === 'ADMIN') return [{ label: 'Usuarios totales', value: this.users.length, note: 'cuentas registradas' }, { label: 'Alumnos', value: this.users.filter((u) => u.rol === 'ALUMNO').length, note: 'en la plataforma' }, { label: 'Padres', value: this.users.filter((u) => u.rol === 'PADRE').length, note: 'tutores activos' }, { label: 'Reportes abiertos', value: open, note: 'requieren seguimiento' }]; if (this.role === 'SOPORTE') return ['PENDIENTE', 'EN_REVISION', 'EN_PROCESO', 'RESUELTO'].map((status) => ({ label: status.replace('_', ' '), value: this.reports.filter((r) => r.estado === status).length, note: 'reportes' })); return [{ label: 'Tareas pendientes', value: this.upcomingTasks.length, note: 'por completar' }, { label: 'Próxima entrega', value: this.upcomingTasks[0]?.fecha ?? '—', note: 'fecha más cercana' }, { label: 'Materias', value: this.subjects.length, note: 'en tu grupo' }, { label: 'Avisos', value: this.notices.length, note: 'publicados' }]; }
  ngOnInit(): void { this.darkMode = document.body.classList.contains('dark'); this.parentChildId = this.user?.hijos?.[0] ?? ''; }
  setSection(section: string): void { this.activeSection = section; this.sidebarOpen = false; }
  toggleTheme(): void { this.darkMode = !this.darkMode; document.body.classList.toggle('dark', this.darkMode); }
  logout(): void { this.auth.logout(); }
  createTask(): void { if (this.role !== 'ALUMNO' || !this.newTaskTitle.trim()) return; const task: Task = { id: this.storage.makeId('t'), alumnoId: this.studentId, titulo: this.newTaskTitle, descripcion: '', materia: this.newTaskSubject || 'Personal', fecha: this.newTaskDate, prioridad: this.newTaskPriority, estado: 'PENDIENTE', fechaCreacion: new Date().toISOString().slice(0, 10) }; this.storage.save('tareas', [...this.allTasks, task]); this.newTaskTitle = ''; this.taskFormVisible = false; }
  toggleTask(task: Task): void { if (this.role !== 'ALUMNO') return; const state: TaskStatus = task.estado === 'COMPLETADA' ? 'PENDIENTE' : 'COMPLETADA'; this.storage.save('tareas', this.allTasks.map((item) => item.id === task.id ? { ...item, estado: state } : item)); }
  deleteTask(task: Task): void { if (this.role === 'ALUMNO' && confirm('¿Eliminar esta tarea?')) this.storage.save('tareas', this.allTasks.filter((item) => item.id !== task.id)); }
  createSubject(): void { if (!this.newSubjectName.trim()) return; this.storage.save('materias', [...this.subjects, { id: this.storage.makeId('m'), nombre: this.newSubjectName, profesor: this.newSubjectTeacher, grupo: this.newSubjectGroup, horario: 'Por definir', aula: this.newSubjectRoom || 'Por definir' }]); this.subjectFormVisible = false; this.newSubjectName = ''; }
  createPlatform(): void { if (!this.newPlatformName.trim() || !this.newPlatformUrl.trim()) return; this.storage.save('plataformas', [...this.platforms, { id: this.storage.makeId('p'), nombre: this.newPlatformName, url: this.newPlatformUrl, descripcion: this.newPlatformDescription, tipo: 'Personal' }]); this.platformFormVisible = false; this.newPlatformName = ''; }
  createNotice(): void { if (!this.newNoticeTitle.trim()) return; this.storage.save('avisos', [...this.notices, { id: this.storage.makeId('av'), titulo: this.newNoticeTitle, contenido: this.newNoticeContent, fecha: '2026-09-15', importancia: this.newNoticeImportance, autor: this.user?.nombre ?? 'Administración' }]); this.noticeFormVisible = false; this.newNoticeTitle = ''; }
  createReport(): void { if (!this.newReportLocation.trim() || !this.newReportDescription.trim()) return; this.storage.save('reportes', [...this.reports, { id: String(this.reports.length + 1).padStart(3, '0'), ubicacion: this.newReportLocation, descripcion: this.newReportDescription, usuarioId: this.user?.id ?? '', fecha: '2026-09-15', estado: 'PENDIENTE', comentarios: [] }]); this.reportFormVisible = false; this.newReportLocation = ''; this.newReportDescription = ''; }
  changeReport(report: { id: string; estado: ReportStatus; comentarios: string[] }, status: ReportStatus): void { this.storage.save('reportes', this.reports.map((item) => item.id === report.id ? { ...item, estado: status } : item)); }
  addComment(report: { id: string }, comment: string): void { if (!comment.trim()) return; this.storage.save('reportes', this.reports.map((item) => item.id === report.id ? { ...item, comentarios: [...item.comentarios, comment] } : item)); }
  createUser(): void { if (!this.newUserName.trim() || !this.newUserEmail.trim()) return; this.storage.save('usuarios', [...this.users, { id: this.storage.makeId('u'), nombre: this.newUserName, email: this.newUserEmail, password: '123456', rol: this.newUserRole, activo: true }]); this.userFormVisible = false; this.newUserName = ''; }
  toggleUser(account: User): void { this.storage.save('usuarios', this.users.map((user) => user.id === account.id ? { ...user, activo: !user.activo } : user)); }
  eventsForDay(day: number): EventItem[] { const date = `2026-09-${String(day).padStart(2, '0')}`; return this.storage.collection('eventos').filter((event) => event.fecha === date); }
}
